/* 
  Función que transfiere dinero de una cuenta a otra
  Se incluye validaciones y 
*/

CREATE FUNCTION TRANSFERIR2 (CTA1 CUENTAS.ID%TYPE, CTA2 CUENTAS.ID%TYPE, MONTO CUENTAS.SALDO%TYPE) 
RETURNS CUENTAS.SALDO%TYPE AS $$

DECLARE
  SALDO_NUEVO CUENTAS.SALDO%TYPE;
  SALDO_DISPONIBLE CUENTAS.saldo%TYPE;
  CUENTA_EXISTE INT;

BEGIN
  SELECT COUNT(*) INTO CUENTA_EXISTE FROM CUENTAS WHERE id = CTA1;
  IF CUENTA_EXISTE <> 1 THEN
    RAISE EXCEPTION 'La cuenta % no existe', CTA1;
  ELSE
    SELECT COUNT(*) INTO CUENTA_EXISTE FROM CUENTAS WHERE id = CTA2;
    IF CUENTA_EXISTE <> 1 THEN
      RAISE EXCEPTION 'La cuenta % no existe', CTA2;
    ELSE
      SELECT SALDO INTO SALDO_DISPONIBLE FROM CUENTAS WHERE ID = CTA1;
      IF SALDO_DISPONIBLE < MONTO THEN
	RAISE EXCEPTION 'No hay fondos suficientes para la transferencia';
      ELSE
	UPDATE CUENTAS SET SALDO = SALDO - MONTO WHERE ID = CTA1;
	UPDATE CUENTAS SET SALDO = SALDO + MONTO WHERE ID = CTA2;
	SELECT SALDO INTO SALDO_NUEVO FROM CUENTAS WHERE ID = CTA2;
	RETURN SALDO_NUEVO;
      END IF;
     END IF;
  END IF;
END;
$$
LANGUAGE PLPGSQL;